---
- name: Docker Operations
  hosts: ec2
  gather_facts: false
  become: true
  tasks:
    - name: Docker Login
      command: docker login -u "{{ DOCKERHUB_USERNAME }}" -p "{{ DOCKERHUB_PASSWORD }}"

    - name: Docker Pull
      command: docker pull {{ container_name }}:{{ tag }}

    - name: Docker Run
      command: docker run -d -p 80:80 --name "{{ container_name }}" "{{ image_name }}:{{ tag }}"
