---
- name: Pull Docker image from Nexus
  hosts: localhost
  become: yes
  tasks:
    - name: Log in to Nexus Docker registry
      docker_login:
        registry_url: "http://localhost:8085"
        username: "admin"
        password: "nexus"

    - name: Pull Docker image
      docker_image:
        name: "http://localhost:8085/doc:v1"
        source: pull
